### ISSUE TITLE
Problems with visualizing polysaccharides

### ISSUE THREAD

**Issue by ONISniperOne** [insilichem/plume_snfg#3]
Hello,

I managed to visualize monosaccharides like SIA and mannose just fine. However when I have polysaccharides, snfg doesn't recognize them? 

Also, when I do matchmaker on 2 proteins, it seems the SNFG representations stay at the original positions instead of the new location of the glycans.

![Screenshot from 2023-09-20 13-58-37](https://github.com/insilichem/tangram_snfg/assets/128614019/2196954a-0383-49fb-b420-5013b8f103b2)

**Comment by jaimergp** [comment]
About (1) no idea, sorry, you might want to check the definitions.py file. About (2), you'll need to ~snfg and then snfg again to recreate them in place.

**Comment by ONISniperOne** [comment]
> About (1) no idea, sorry, you might want to check the definitions.py file. About (2), you'll need to ~snfg and then snfg again to recreate them in place.

Do you know who I can reach out to about (1)? I'm not too sure what to do with the definitions.py
